version: '3.4'

services:
  gauss.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "20442:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro


  gauss.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "43080:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro