version: '3.4'

services:
  gauss.tccunifaat.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "20442:8080"
      - "20443:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro


  gauss.tccunifaat.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro